version: "3"
services:
  weeb:
    restart: always
    build: .
    image: hatem2020/weeb:latest
    ports:
      - 80:3000
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
